const Blog = () => {
    return (
        <section className='flex justify-center items-center min-h-screen mt-5' >
            <div className="text-white w-1/2 text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id cursus metus aliquam eleifend mi. Purus faucibus ornare suspendisse sed nisi lacus. Habitant morbi tristique senectus et netus et. Lobortis feugiat vivamus at augue eget arcu dictum varius. Phasellus faucibus scelerisque eleifend donec pretium. Adipiscing elit duis tristique sollicitudin nibh sit amet. Facilisis gravida neque convallis a cras semper auctor neque vitae. Sed euismod nisi porta lorem mollis aliquam ut. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Justo eget magna fermentum iaculis eu non. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi.

                Porta nibh venenatis cras sed felis eget velit. Non nisi est sit amet. Faucibus a pellentesque sit amet porttitor eget dolor. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Suspendisse potenti nullam ac tortor vitae purus faucibus. Sed nisi lacus sed viverra tellus in. Senectus et netus et malesuada fames ac. Lacus viverra vitae congue eu consequat ac felis donec et. Tortor consequat id porta nibh. In pellentesque massa placerat duis ultricies lacus sed.

                Vel quam elementum pulvinar etiam non quam lacus. Amet consectetur adipiscing elit ut. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Posuere lorem ipsum dolor sit amet. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Eu augue ut lectus arcu. Ipsum nunc aliquet bibendum enim. At auctor urna nunc id cursus metus aliquam eleifend mi. Vestibulum morbi blandit cursus risus at ultrices mi. Turpis cursus in hac habitasse platea dictumst. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Sed augue lacus viverra vitae congue eu. Dignissim convallis aenean et tortor at risus viverra adipiscing. Nec feugiat nisl pretium fusce. Velit ut tortor pretium viverra. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna.

                Tellus cras adipiscing enim eu turpis. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Auctor eu augue ut lectus arcu bibendum at. Nibh praesent tristique magna sit amet purus. Lectus proin nibh nisl condimentum id. Posuere ac ut consequat semper viverra nam. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Pellentesque adipiscing commodo elit at. Elementum nisi quis eleifend quam adipiscing. Sed id semper risus in. Ut tellus elementum sagittis vitae et leo. Ut lectus arcu bibendum at. Ante metus dictum at tempor commodo ullamcorper. Vitae elementum curabitur vitae nunc. Nunc eget lorem dolor sed viverra ipsum nunc. Nisl vel pretium lectus quam id leo. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Sociis natoque penatibus et magnis dis parturient montes nascetur.

                Urna molestie at elementum eu facilisis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Vel eros donec ac odio tempor orci dapibus ultrices in. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Nulla aliquet porttitor lacus luctus. Morbi tristique senectus et netus et malesuada fames ac turpis. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Nulla aliquet porttitor lacus luctus accumsan tortor. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Justo nec ultrices dui sapien eget mi proin sed libero. Lectus nulla at volutpat diam ut. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Egestas integer eget aliquet nibh praesent tristique magna sit. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Sed vulputate odio ut enim blandit volutpat. Eu mi bibendum neque egestas congue quisque egestas.

                Eu augue ut lectus arcu bibendum at. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Iaculis urna id volutpat lacus laoreet non. Amet purus gravida quis blandit. Convallis convallis tellus id interdum velit laoreet. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Nam aliquam sem et tortor consequat id porta. Eu augue ut lectus arcu bibendum at varius. Lobortis scelerisque fermentum dui faucibus in ornare quam. Fusce ut placerat orci nulla pellentesque dignissim. Luctus venenatis lectus magna fringilla urna porttitor. Nunc eget lorem dolor sed. Quis blandit turpis cursus in hac habitasse platea. Ultrices mi tempus imperdiet nulla. Elit pellentesque habitant morbi tristique senectus.

                Pharetra sit amet aliquam id. Ac turpis egestas sed tempus urna et pharetra pharetra. Donec ac odio tempor orci dapibus ultrices in iaculis. Fermentum et sollicitudin ac orci phasellus egestas. Etiam tempor orci eu lobortis. Ipsum suspendisse ultrices gravida dictum fusce. Ac turpis egestas integer eget aliquet. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Suspendisse sed nisi lacus sed viverra tellus. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Lacinia quis vel eros donec ac odio. Ut sem nulla pharetra diam sit amet nisl suscipit. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi.

                Condimentum lacinia quis vel eros donec ac odio tempor. Magna etiam tempor orci eu. Eu turpis egestas pretium aenean pharetra magna ac placerat. Duis convallis convallis tellus id interdum velit. Erat nam at lectus urna duis convallis convallis tellus. Mauris commodo quis imperdiet massa. Vitae congue eu consequat ac felis. Curabitur vitae nunc sed velit dignissim sodales ut. Viverra mauris in aliquam sem fringilla. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Dolor morbi non arcu risus quis varius quam. Dignissim diam quis enim lobortis. Facilisis sed odio morbi quis commodo odio aenean. Aenean et tortor at risus. Enim praesent elementum facilisis leo vel. Feugiat nisl pretium fusce id velit ut tortor. Tempor orci dapibus ultrices in iaculis. Libero volutpat sed cras ornare. Placerat orci nulla pellentesque dignissim enim.

                Rhoncus dolor purus non enim. Sed libero enim sed faucibus turpis in eu mi bibendum. Massa vitae tortor condimentum lacinia quis vel eros donec. Vitae nunc sed velit dignissim sodales. Tristique nulla aliquet enim tortor at auctor urna nunc id. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Phasellus vestibulum lorem sed risus ultricies tristique. Gravida neque convallis a cras semper auctor neque vitae. Euismod lacinia at quis risus sed. Imperdiet dui accumsan sit amet nulla. Lorem ipsum dolor sit amet consectetur adipiscing elit. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Volutpat odio facilisis mauris sit amet massa vitae tortor. Congue eu consequat ac felis donec. Nulla facilisi cras fermentum odio eu feugiat pretium. Velit egestas dui id ornare.

                Consectetur lorem donec massa sapien. Fermentum posuere urna nec tincidunt praesent semper. Nibh venenatis cras sed felis eget velit aliquet sagittis. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Ac felis donec et odio pellentesque diam volutpat. Sed augue lacus viverra vitae congue eu. Sit amet mattis vulputate enim nulla aliquet porttitor. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Sit amet consectetur adipiscing elit ut. Vulputate odio ut enim blandit. Cursus metus aliquam eleifend mi in. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Leo duis ut diam quam nulla. Ornare quam viverra orci sagittis. Sit amet risus nullam eget felis eget nunc lobortis. Amet dictum sit amet justo. Quis auctor elit sed vulputate mi. Imperdiet nulla malesuada pellentesque elit eget. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Odio euismod lacinia at quis risus sed vulputate odio ut.
            </div>
        </section>
    )
}

export default Blog
